export type LedgerReward = string[][];

export type LedgerRewards = {
  [factionId: string]: LedgerReward;
}

// data from https://seaofthieves.wiki.gg/wiki/Emissary_Ledger#Rewards
const ledgerRewards: LedgerRewards = {
  'GoldHoarders': [
    [
      'Gold Hoarders Inaugural Captain Sails',
      'Tribute Peak Figurehead',
      'Tribute Peak Wheel',
      'Tribute Peak Sails',
      'Tribute Peak Cutlass',
      'Tribute Peak Eye of Reach',
      'Tribute Peak Concertina',
      'Tribute Peak Banjo',
      'Tribute Peak Tankard',
      'Tribute Peak Bucket',
      'Tribute Peak Compass',
      'Tribute Peak Lantern',
    ],
    [
      'Gold Hoarders Inaugural Marauder Sails',
      'Tribute Peak Hull',
      'Tribute Peak Cannons',
      'Tribute Peak Capstan',
      'Tribute Peak Pistol',
      'Tribute Peak Blunderbuss',
      'Tribute Peak Drum',
      'Tribute Peak Hurdy-Gurdy',
      'Tribute Peak Fishing Rod',
      'Tribute Peak Spyglass',
      'Tribute Peak Shovel',
      'Tribute Peak Speaking Trumpet',
    ],
    [
      'Emissary of Gold Seafarers',
      'Seafarer of Sealed Stashes',
      "Seafarer of Rogues' Riddles",
      'Seafarer of Vaulted Valuables',
      'Seafarer of Recovered Riches',
      'Seafarer of Cursed Coins',
      'Seafarer of Tallied Tribute',
      'Seafarer of Curious Caskets',
      'Seafarer of Golden Games',
      'Seafarer of Hidden Hoards',
      'Seafarer of Brimming Bounty',
      'Seafarer of Opulent Opportunities',
    ]
  ],
  'OrderOfSouls': [
    [
      'Order of Souls Inaugural Grandee Sails',
      'Relic of Darkness Figurehead',
      'Relic of Darkness Wheel',
      'Relic of Darkness Sails',
      'Relic of Darkness Cutlass',
      'Relic of Darkness Eye of Reach',
      'Relic of Darkness Concertina',
      'Relic of Darkness Banjo',
      'Relic of Darkness Tankard',
      'Relic of Darkness Bucket',
      'Relic of Darkness Compass',
      'Relic of Darkness Lantern',
    ],
    [
      'Order of Souls Inaugural Chief Sails',
      'Relic of Darkness Hull',
      'Relic of Darkness Cannons',
      'Relic of Darkness Capstan',
      'Relic of Darkness Pistol',
      'Relic of Darkness Blunderbuss',
      'Relic of Darkness Drum',
      'Relic of Darkness Hurdy-Gurdy',
      'Relic of Darkness Fishing Rod',
      'Relic of Darkness Spyglass',
      'Relic of Darkness Shovel',
      'Relic of Darkness Speaking Trumpet',
    ],
    [
      'Emissary of Mystic Mercenaries',
      'Mercenary of Sundered Skulls',
      'Mercenary of Ghostly Galleons',
      'Mercenary of Stray Spirits',
      'Mercenary of Fated Foresight',
      'Mercenary of Spectral Supplies',
      'Mercenary of Remarkable Relics',
      'Mercenary of of Inky Insight',
      'Mercenary of Scorching Skulls',
      'Mercenary of Mysterious Missions',
      'Mercenary of Supernatural Skirmishes',
      'Mercenary of Terrible Tides',
    ],
  ],
  'MerchantAlliance': [
    [
      'Merchant Alliance Inaugural Admiral Sails',
      'Merchant Ambassador Figurehead',
      'Merchant Ambassador Wheel',
      'Merchant Ambassador Sails',
      'Merchant Ambassador Cutlass',
      'Merchant Ambassador Eye of Reach',
      'Merchant Ambassador Concertina',
      'Merchant Ambassador Banjo',
      'Merchant Ambassador Tankard',
      'Merchant Ambassador Bucket',
      'Merchant Ambassador Compass',
      'Merchant Ambassador Lantern',
    ],
    [
      'Merchant Alliance Inaugural Commander Sails',
      'Merchant Ambassador Hull',
      'Merchant Ambassador Cannons',
      'Merchant Ambassador Capstan',
      'Merchant Ambassador Pistol',
      'Merchant Ambassador Blunderbuss',
      'Merchant Ambassador Drum',
      'Merchant Ambassador Hurdy-Gurdy',
      'Merchant Ambassador Fishing Rod',
      'Merchant Ambassador Spyglass',
      'Merchant Ambassador Shovel',
      'Merchant Ambassador Speaking Trumpet'
    ],
    [
      'Emissary of Merchant Cadets',
      'Cadet of Curious Cargo',
      'Cadet of Salvaged Shipments',
      'Cadet of Triumphant Trades',
      'Cadet of Precision Plans',
      'Cadet of Coral Coffers',
      'Cadet of Fizzing Fireworks',
      'Cadet of Required Resources',
      'Cadet of Bartered Bait',
      'Cadet of Crafty Carrying',
      'Cadet of Fastidious Ferrying',
      'Cadet of Championing Charts',
    ],
  ],
  'ReapersBones': [
    [
      "Reaper's Bones Inaugural Master Sails",
      'Masked Renegade Figurehead',
      'Masked Renegade Wheel',
      'Masked Renegade Sails',
      'Masked Renegade Cutlass',
      'Masked Renegade Eye of Reach',
      'Masked Renegade Concertina',
      'Masked Renegade Banjo',
      'Masked Renegade Tankard',
      'Masked Renegade Bucket',
      'Masked Renegade Compass',
      'Masked Renegade Lantern',
    ],
    [
      "Reaper's Bones Inaugural Keeper Sails",
      'Masked Renegade Hull',
      'Masked Renegade Cannons',
      'Masked Renegade Capstan',
      'Masked Renegade Pistol',
      'Masked Renegade Blunderbuss',
      'Masked Renegade Drum',
      'Masked Renegade Hurdy-Gurdy',
      'Masked Renegade Fishing Rod',
      'Masked Renegade Spyglass',
      'Masked Renegade Shovel',
      'Masked Renegade Speaking Trumpet',
    ],
    [
      'Emissary of Eternal Servants',
      'Servant of Splintered Ships',
      'Servant of Taken Treasures',
      'Servant of Fearless Freedom',
      'Servant of Masked Mystique',
      'Servant of Fiery Fates',
      'Servant of Soulflame Schemes',
      'Servant of Cursed Chalices',
      "Servant of Flameheart's Fear",
      "Servant of Flameheart's Fear (2)",
      'Servant of Whispering Warriors',
      'Servant of Clandestine Conflict',
    ],
  ],
  'AthenasFortune': [
    [
      "Athena's Fortune Inaugural Legend Sails",
      'Legendary Spirit Cutlass',
      'Legendary Spirit Eye of Reach',
      "Magpie's Glory Wheel",
      "Magpie's Glory Hull",
      "Magpie's Glory Sails",
      "Magpie's Glory Concertina",
      "Magpie's Glory Banjo",
      "Magpie's Glory Tankard",
      "Magpie's Glory Bucket",
      "Magpie's Glory Compass",
      "Magpie's Glory Lantern",
    ],
    [
      "Athena's Fortune Inaugural Guardian Sails", 
      'Legendary Spirit Pistol',
      'Legendary Spirit Blunderbuss',
      "Magpie's Glory Capstan",
      "Magpie's Glory Figurehead",
      "Magpie's Glory Cannons",
      "Magpie's Glory Drum",
      "Magpie's Glory Hurdy-Gurdy",
      "Magpie's Glory Fishing Rod",
      "Magpie's Glory Spyglass",
      "Magpie's Glory Shovel",
      "Magpie's Glory Speaking Trumpet",
    ],
    [
      'Emissary of Fortune Voyagers',
      'Voyager of Pirate Prowess',
      'Voyager of Sworn Secrets',
      'Voyager of Valiant Vessels',
      'Voyager of Ghostly Glory',
      'Voyager of Ancient Art',
      'Voyager of Boundless Bravery',
      "Voyager of Bravery's Blessing",
      'Voyager of Fated Fortune',
      'Voyager of Thrice-Thrust Blades',
      'Voyager of Esteemed Eminence',
      'Voyager of Defended Dignity',
    ],
  ],
  'Guilds': [
    [
      "‘The Relentless Onslaught’",
      "‘The Constellation's Secret’",
      "‘An Ocean of Siren Song’",
      "‘Secrets of the Ancient Flame’",
    ],
    [
      "‘Guild's First Coin’",
      "‘Astrolabe of Ancient Stars’",
      "‘Mysterious Siren Carving’",
      "‘Dark Hand of Fate’",
    ],
    [
      'Guild of Captured Winds',
      'Guild of Conquered Horizons',
      'Guild of Fearsome Depths',
      'Guild of Fiery Spirits'
    ]
  ]
};

export function getLedgerMaxLevel(factionId: string): number {
  const rewards = ledgerRewards[factionId];
  return rewards ? rewards[0].length : 12;
}

export function getLedgerLevel(factionId: string, bandIndex: number, title: string): number {
  const rewards = ledgerRewards[factionId];
  return rewards ? (rewards[bandIndex].indexOf(title) + 1) : 0;
}
