name: Release Build

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: npm run build
      - name: Package extension
        run: npm run package
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/sot-dashboard-${{ github.ref_name }}.zip

permissions:
  contents: write
